# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-22 13:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feature_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 22, 13, 11, 13, 634854, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 22, 13, 11, 13, 633010, tzinfo=utc), null=True),
        ),
    ]
