# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 14:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feature_requests', '0007_auto_20190106_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 7, 14, 1, 40, 357535, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 7, 14, 1, 40, 355651, tzinfo=utc), null=True),
        ),
    ]
