# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-03 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feature_requests', '0012_auto_20190103_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 3, 18, 33, 23, 946734, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 3, 18, 33, 23, 944898, tzinfo=utc), null=True),
        ),
    ]
