# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-07 08:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 7, 8, 32, 56, 21854, tzinfo=utc), null=True),
        ),
    ]
