# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 12:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue_tracker', '0004_auto_20181213_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='likes',
        ),
        migrations.AlterField(
            model_name='issue',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 13, 12, 18, 47, 684270, tzinfo=utc), null=True),
        ),
        migrations.RemoveField(
            model_name='issue',
            name='votes',
        ),
        migrations.AddField(
            model_name='issue',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
