# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-06 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0004_auto_20190106_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 6, 16, 2, 7, 166644, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 6, 16, 2, 7, 164537, tzinfo=utc), null=True),
        ),
    ]
