# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0009_auto_20181213_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='fixed',
            new_name='done',
        ),
        migrations.AlterField(
            model_name='issue',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 13, 16, 6, 0, 900143, tzinfo=utc), null=True),
        ),
    ]
