# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0011_auto_20181217_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 18, 11, 55, 49, 845292, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='issue',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 18, 11, 55, 49, 843257, tzinfo=utc), null=True),
        ),
    ]
