# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-03 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0028_auto_20190103_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 3, 17, 19, 48, 988335, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 3, 17, 19, 48, 985605, tzinfo=utc), null=True),
        ),
    ]
