# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-06 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20190106_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
