# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190106_1305'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlepayment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.UserProfile'),
        ),
    ]
