# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-23 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20181222_1429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SinglePayment',
            new_name='Payment',
        ),
        migrations.RenameModel(
            old_name='SinglePaymentLineItem',
            new_name='PaymentLineItem',
        ),
    ]
