# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-23 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20181223_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlineitem',
            name='feature_request',
        ),
        migrations.RemoveField(
            model_name='paymentlineitem',
            name='single_payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentLineItem',
        ),
    ]
