# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-03 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature_requests', '0011_auto_20190103_1714'),
        ('checkout', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='feature_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feature_requests.FeatureRequest'),
        ),
    ]
