# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-03 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20181223_1151'),
        ('feature_requests', '0012_auto_20190103_1719'),
        ('checkout', '0006_payment_feature_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=40)),
                ('postcode', models.CharField(max_length=15)),
                ('town_or_city', models.CharField(max_length=30)),
                ('street_address1', models.CharField(max_length=40)),
                ('street_address2', models.CharField(max_length=40)),
                ('county', models.CharField(blank=True, max_length=30)),
                ('date', models.DateField()),
                ('feature_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feature_requests.FeatureRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='feature_request',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
