# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-03 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature_requests', '0014_auto_20190103_1849'),
        ('checkout', '0007_auto_20190103_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePaymentLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_requests.FeatureRequest')),
            ],
        ),
        migrations.RemoveField(
            model_name='singlepayment',
            name='feature_request',
        ),
        migrations.RemoveField(
            model_name='singlepayment',
            name='user',
        ),
        migrations.AddField(
            model_name='singlepaymentlineitem',
            name='single_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.SinglePayment'),
        ),
    ]
