# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-06 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
