# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-23 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_billngaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billngaddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='BillngAddress',
        ),
    ]
